---
# tasks file for common
- name: "Install prereq packages"
  apt:
    pkg: 
    - python-netaddr
    - python3-psycopg2
    - libpq-dev
    - nmap
    - git
    - build-essential
    state: present
    update_cache: yes
  tags: common

- name: update hosts file by appending records
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'hosts.j2') }}"
    state: present
  tags: common

